### ISSUE TITLE
"from pymecompress import bcl" fails "illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by adrianhollow** [python-microscopy/pymecompress#7]
**Description:**

When opening dh5viewer (supertile) from PYME, the program ends with the message: "illegal instruction (core dumped)". Debugging shows that the program can't progress beyond line 28 in PYME/IO/PZFFormat.py:

from pymecompress import bcl

**To Reproduce:**

Open dh5viewer as described, or perhaps just try the import.

**Platform:**

OS: Ubuntu 20.04
CPU: amd ryzen 7 3700x 8 core
Python Version: 3.7

**Comment by adrianhollow** [comment]
Building from source appears to resolve this issue.

**Comment by barentine** [comment]
Reopening if we can: @adrianhollow mentioned having conda installed PYME originally - we might need to check on py37 @David-Baddeley
