### ISSUE TITLE
Can't import `bcl` on fresh Debian install

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/pymecompress#9]
I compiled `pymecompress` locally on my machine. I receive the following traceback when I run `from pymecompress import bcl`.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/pyme/lib/python3.7/site-packages/pymecompress-0.3.0-py3.7-linux-x86_64.egg/pymecompress/__init__.py", line 2, in <module>
    from .bcl import HuffmanCompress, HuffmanCompressQuant, HuffmanDecompress
ImportError: /opt/conda/envs/pyme/lib/python3.7/site-packages/pymecompress-0.3.0-py3.7-linux-x86_64.egg/pymecompress/bcl.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _quantize_u16_AVX
```

**Comment by David-Baddeley** [comment]
Same issue is messing with our tests at present ... suspect it's due to a change in how run-time avx detection is done.

**Comment by David-Baddeley** [comment]
Hmm, odd - just tried a local linux install and it works fine. How old is the linux machine you tested on? Any chance it's pre-avx?

Also, what numpy version did you compile with - could be that it needs a more recent numpy. Maybe the output of `conda list` and `cat /proc/cpuinfo`

**Comment by zacsimile** [comment]
I tried it on a Docker Debian install. The host computer was built in 2014 and has an Intel Core i7-4820K, which appears to support AVX. Outputs of `cat /proc/cpuinfo` and `conda list` for the Docker machine are below.

I will say I also just now tried it on the host machine (Ubuntu 20.04.4 LTS) and received the same traceback.

<details>
<summary>cat /proc/cpuinfo</summary>
<pre>
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
stepping	: 4
microcode	: 0x42e
cpu MHz		: 3197.473
cache size	: 10240 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 7404.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
stepping	: 4
microcode	: 0x42e
cpu MHz		: 2929.588
cache size	: 10240 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 7404.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
stepping	: 4
microcode	: 0x42e
cpu MHz		: 3485.691
cache size	: 10240 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 7404.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
stepping	: 4
microcode	: 0x42e
cpu MHz		: 3163.652
cache size	: 10240 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 7404.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 4
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
stepping	: 4
microcode	: 0x42e
cpu MHz		: 2946.424
cache size	: 10240 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 7404.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 5
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
stepping	: 4
microcode	: 0x42e
cpu MHz		: 3517.551
cache size	: 10240 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 7404.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 6
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
stepping	: 4
microcode	: 0x42e
cpu MHz		: 3320.740
cache size	: 10240 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 5
initial apicid	: 5
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 7404.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
stepping	: 4
microcode	: 0x42e
cpu MHz		: 3044.563
cache size	: 10240 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 7404.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
</pre>
</details>

<details>
<summary>conda list</summary>
<pre>
# packages in environment at /opt/conda/envs/pyme:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0    anaconda
babel                     2.8.0                      py_0    anaconda
blas                      1.0                    openblas    anaconda
blosc                     1.19.0               hd408876_0    anaconda
brotlipy                  0.7.0           py37h7b6447c_1000    anaconda
bzip2                     1.0.8                h7b6447c_0    anaconda
ca-certificates           2020.10.14                    0    anaconda
cairo                     1.14.12              h8948797_3  
certifi                   2020.6.20                py37_0    anaconda
cffi                      1.14.3           py37he30daa8_0    anaconda
chardet                   3.0.4                 py37_1003    anaconda
cheroot                   8.4.5                    py37_0    anaconda
cherrypy                  18.6.0                   py37_0    anaconda
cloudpickle               1.6.0                      py_0    anaconda
cryptography              3.1.1            py37h1ba5d50_0    anaconda
cycler                    0.10.0                   py37_0    anaconda
cython                    0.29.21          py37he6710b0_0    anaconda
cytoolz                   0.11.0           py37h7b6447c_0    anaconda
dask-core                 2.30.0                     py_0    anaconda
dbus                      1.13.18              hb2f20db_0    anaconda
decorator                 4.4.2                      py_0    anaconda
django                    2.1.7                    py37_0    anaconda
docutils                  0.16                     py37_1    anaconda
expat                     2.2.10               he6710b0_2    anaconda
fftw                      3.3.8                h7b6447c_3    anaconda
fontconfig                2.13.0               h9420a91_0    anaconda
freetype                  2.10.4               h5ab3b9f_0    anaconda
future                    0.18.2                   py37_1    anaconda
glib                      2.66.1               h92f7085_0    anaconda
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
hdf5                      1.10.4               hb1b8bf9_0    anaconda
icu                       58.2                 he6710b0_3    anaconda
idna                      2.10                       py_0    anaconda
ifaddr                    0.1.6                      py_0    david_baddeley
imageio                   2.9.0                      py_0    anaconda
imagesize                 1.2.0                      py_0    anaconda
jaraco.classes            3.1.0                      py_0    anaconda
jaraco.collections        3.0.0                      py_0    anaconda
jaraco.functools          3.0.1                      py_0    anaconda
jaraco.text               3.2.0                    py37_1    anaconda
jinja2                    2.11.2                     py_0    anaconda
joblib                    0.17.0                     py_0    anaconda
jpeg                      9b                   habf39ab_1    anaconda
kiwisolver                1.2.0            py37hfd86e86_0    anaconda
lcms2                     2.11                 h396b838_0    anaconda
ld_impl_linux-64          2.33.1               h53a641e_7    anaconda
libedit                   3.1.20191231         h14c3975_1    anaconda
libffi                    3.3                  he6710b0_2    anaconda
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libopenblas               0.3.10               h5a2b251_0    anaconda
libpng                    1.6.37               hbc83047_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libtiff                   4.1.0                h2733197_1    anaconda
libuuid                   1.0.3                h1bed415_2    anaconda
libxcb                    1.14                 h7b6447c_0    anaconda
libxml2                   2.9.10               hb55368b_3    anaconda
lz4-c                     1.9.2                heb0550a_3    anaconda
lzo                       2.10                 h7b6447c_2    anaconda
markupsafe                1.1.1            py37h14c3975_1    anaconda
matplotlib                3.2.2                         0    anaconda
matplotlib-base           3.2.2            py37hef1b27d_0    anaconda
mock                      4.0.2                      py_0    anaconda
more-itertools            8.5.0                      py_0    anaconda
mpld3                     v0.3                     py37_0    david_baddeley
ncurses                   6.2                  he6710b0_1    anaconda
networkx                  2.5                        py_0    anaconda
numexpr                   2.7.1            py37h7ea95a0_0    anaconda
numpy                     1.19.1           py37h30dfecb_0    anaconda
numpy-base                1.19.1           py37h75fe3a5_0    anaconda
olefile                   0.46                     py37_0    anaconda
openssl                   1.1.1h               h7b6447c_0    anaconda
packaging                 20.4                       py_0    anaconda
pandas                    1.1.3            py37he6710b0_0    anaconda
pcre                      8.44                 he6710b0_0    anaconda
pillow                    8.0.0            py37h9a89aac_0    anaconda
pip                       20.2.4                   py37_0    anaconda
pixman                    0.40.0               h7b6447c_0    anaconda
portend                   2.6                        py_0    anaconda
psutil                    5.7.2            py37h7b6447c_0    anaconda
pycairo                   1.19.1           py37h2a1e443_0    anaconda
pycparser                 2.20                       py_2    anaconda
pyfftw                    v0.11.1          py37hd844fa7_0    david_baddeley
pygments                  2.7.1                      py_0    anaconda
pymecompress              0.3.0                    pypi_0    pypi
pyopenssl                 19.1.0                     py_1    anaconda
pyparsing                 2.4.7                      py_0    anaconda
pyqt                      5.9.2            py37h22d08a2_1    anaconda
pysocks                   1.7.1                    py37_1    anaconda
pytables                  3.6.1            py37h71ec239_0    anaconda
python                    3.7.9                h7579374_0    anaconda
python-dateutil           2.8.1                      py_0    anaconda
python-microscopy         22.1.12.post0.dev0          pypi_0    pypi
pytz                      2020.1                     py_0    anaconda
pywavelets                1.1.1            py37h7b6447c_2    anaconda
pyyaml                    5.3.1            py37h7b6447c_1    anaconda
qt                        5.9.7                h5867ecd_1  
readline                  8.0                  h7b6447c_0    anaconda
repoze.lru                0.7                      py37_0    anaconda
requests                  2.24.0                     py_0    anaconda
routes                    2.4.1                      py_1    anaconda
scikit-image              0.17.2           py37hdf5156a_0    anaconda
scikit-learn              0.23.2           py37h0573a6f_0    anaconda
scipy                     1.7.3            py37h492baa0_0  
setuptools                50.3.0           py37hb0f4dca_1    anaconda
simplejson                3.17.2           py37h7b6447c_0    anaconda
sip                       4.19.24          py37he6710b0_0    anaconda
six                       1.15.0                     py_0    anaconda
snappy                    1.1.8                he6710b0_0    anaconda
snowballstemmer           2.0.0                      py_0    anaconda
sphinx                    3.2.1                      py_0    anaconda
sphinxcontrib-applehelp   1.0.2                      py_0    anaconda
sphinxcontrib-devhelp     1.0.2                      py_0    anaconda
sphinxcontrib-htmlhelp    1.0.3                      py_0    anaconda
sphinxcontrib-jsmath      1.0.1                      py_0    anaconda
sphinxcontrib-qthelp      1.0.3                      py_0    anaconda
sphinxcontrib-serializinghtml 1.1.4                      py_0    anaconda
sqlite                    3.33.0               h62c20be_0    anaconda
tempora                   4.0.0                      py_0    anaconda
threadpoolctl             2.1.0              pyh5ca1d4c_0    anaconda
tifffile                  2020.10.1        py37hdd07704_2    anaconda
tk                        8.6.10               hbc83047_0    anaconda
toolz                     0.11.1                     py_0    anaconda
toposort                  1.5                      py37_3    david_baddeley
tornado                   6.0.4            py37h7b6447c_1    anaconda
ujson                     4.0.1            py37he6710b0_0    anaconda
urllib3                   1.25.11                    py_0    anaconda
wheel                     0.35.1                     py_0    anaconda
xz                        5.2.5                h7b6447c_0    anaconda
yaml                      0.2.5                h7b6447c_0    anaconda
zc.lockfile               2.0                        py_0    anaconda
zeroconf                  0.23.0                   py37_3    david_baddeley
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.4.4                h0b5b093_3    anaconda
</pre>
</details>

**Comment by zacsimile** [comment]
OK I did another install and now it works on my Ubuntu install and I can't get the error to appear again, even if I delete everything. I have no idea why. Still a problem on Docker.

**Comment by David-Baddeley** [comment]
OK, for reference, my numpy version where it works is 1.21.2. Wonder if it's work checking that in the docker. I think the numpy dispatch magic that I'm using might be fairly new.

**Comment by zacsimile** [comment]
Yep, that fixed it. `numpy>=1.21.2`.
